version: "3.6"

services:
  ### MINIO Server #########################################
  minio:
    container_name: minio
    restart: unless-stopped
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    volumes:
      - ./data:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_REGION_NAME: us-east-1
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: secret
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
